### ISSUE TITLE
Enum not found causes javascript to throw error.

### ISSUE THREAD

**Issue by richardmeester** [tieniber/DataGridColumnSearch#5] opened 2017-02-18 12:49 UTC
When fields are not found, the return of empty values is not checked for valid returns.  I.e. in _addEnumSearchBox ()

the following code is used:
		if (mx.meta) {
				enumMap = mx.meta.getEntity(columnEntity).getEnumMap(columnAttribute); //used in 6.10.3
			} else {
				enumMap = mx.metadata.getEntity(columnEntity).getEnumMap(columnAttribute); //used in 5.20
			}

I am using 6.5.1 modeler and from testing mx.meta is used, however the enum is not found and returns null.
However, the code does not check for null values and as a result the script hangs.

I added the following after the code above, which workes around the issue  (by not placing a search box) but the real issue obviously is that the enum is not found in 651

			if (!enumMap)
			{
				return;
			}

Think in general it is a good idea to check return values if used further down the code.

**Comment by tieniber** [comment] 2017-02-21 15:13
Agreed it's best practice to check values before using them. In this case, the outcome of doing so doesn't help much - the widget still doesn't fully function as designed.

Will investigate.

**Comment by tieniber** [comment] 2017-02-21 16:22
I ran the test project in 6.5.1 and cannot reproduce this error.

mx.meta.getEntity() exists in 6.5.1 and does not return null for me. I can't figure out why it would for you. Can you share any additional details about your project, or perhaps share a test project?

**Comment by tieniber** [comment] 2017-03-31 19:11
I'm going to close this issue as I cannot reproduce it. If you can supply instructions to reproduce, I will re-open and investigate.

**Closed by tieniber** 2017-03-31 19:11 UTC

**Comment by richardmeester** [comment] 2017-04-01 09:16
I found the issue.  It was the wrong entity set in the configuration which resulted in no object being returned.

So in that respect it is no error but the problem is that when this happens in development the whole page will not load and everything stops,  which makes it hard to find out.  Stable code would generate an error and continue.

Regards,
Richard. 
Sent from my iPhone, so excuse the typos.


On 31 Mar 2017, at 21:02, tieniber <notifications@github.com <mailto:notifications@github.com> > wrote:

I'm going to close this issue as I cannot reproduce it. If you can supply instructions to reproduce, I will re-open and investigate.
